### ISSUE TITLE
Improved display of tags & pairs

### ISSUE THREAD

**Issue by filiptibell** [alicesaidhi/jabby#9]
Right now, when inspecting an entity, jabby displays all values in a table like `Key | Value`, but I think tags & pairs in jecs could benefit from being displayed separately since the `Value` part is always `tag`.
Maybe it could be in a separate list below the normal data, similar to how the properties widget in studio displays CollectionService tags.

**Comment by alicesaidhi** [comment]
Implemented with https://github.com/alicesaidhi/jabby/commit/cdbd4bf768becb439d451eaec57b5e979554a766
